[build]
  command = "npm run build" # Replace with your build command if needed
  functions = "functions"   # The directory containing your serverless functions

[dev]
  functionsPort = 34567     # Port for local function development
